### ISSUE TITLE
is kafka's zero copy already implemented?

### ISSUE THREAD

**Issue by sunface** [travisjeffery/jocko#102]
Great project! But i have't seen any content about kafka's zero copy

**Comment by robusto** [comment]
Also curious about this. Seems like the answer is "no" at the moment, looking at the commitlog sub-package. 

Kafka relies on the "sendfile" syscall for the zero-copy and seems important for consumer groups implementation.

**Comment by allyraza** [comment]
also what I have seen missing is the partitions or shards there is no support for partitions, which is really vital for scalability

**Comment by travisjeffery** [comment]
Jocko definitely has partitions. But no it doesn't support zero copy because there's no good implementation of zero copy for Go yet.

**Comment by thumbsized** [comment]
maybe https://github.com/acln0/zerocopy
