### ISSUE TITLE
Please consider adding vendor dir to next release

### ISSUE THREAD

**Issue by dinapappor** [travisjeffery/jocko#108]
Hi!

I am developing a port for FreeBSD where network access is not allowed during build phase. Thus I have no possibility of running go get or deps ensure. Therefor it would be very cool if vendor dir could be added. It would not only benefit FreeBSD, but it'd ensure consistency with other operating systems as well.

**Comment by flowchartsman** [comment]
You could also package the port using `go mod vendor` and then build it with `-mod vendor`

**Comment by leoluk** [comment]
Vendor directories unnecessarily bloat the repository and are a relict of pre-`go mod` dependency management. 

With modules, it's possible to set up a local module package that packages are pulled from rather than the network.

**Comment by travisjeffery** [comment]
Using Go modules now, don't intend to vendor.
