### ISSUE TITLE
go get github.com/travisjeffery/jocko fails

### ISSUE THREAD

**Issue by mlegenhausen** [travisjeffery/jocko#14]
This is the first command described in `examples/cluster`.

Following error message:

```
package github.com/travisjeffery/jocko: no buildable Go source files in /go/src/github.com/travisjeffery/jocko
````

I want to run jocko in docker but it fails on the first command. The same command fails on macOS and I testet multiple go versions from 1.6.4 to 1.8rc2.

There is my used docker file for reproduction purpose:

```Dockerfile
FROM golang:1.7.4-alpine

RUN apk --no-cache add git

RUN go get github.com/travisjeffery/jocko
```

**Comment by travisjeffery** [comment]
Go logs that error but still gets the repo. You can add /... to the end so it doesn't complain. I'll update the docs. So it would be:

```
RUN go get github.com/travisjeffery/jocko/...
```

**Comment by briansorahan** [comment]
@travisjeffery I tried this today and saw this error:

```
go get github.com/travisjeffery/jocko/...
```

```
# github.com/travisjeffery/jocko/log
../../../go/src/github.com/travisjeffery/jocko/log/log.go:52:9: undefined: "upspin.io/log".NewStdLogger
```
