### ISSUE TITLE
Warning on clone

### ISSUE THREAD

**Issue by phreed** [travisjeffery/jocko#146]
https://github.com/travisjeffery/jocko/blob/master/README.md
Indicates that ...
`$ go get github.com/travisjeffery/jocko`
... should be used to clone the jacko source.
It does that but with a warning that...

> "can't load package: package github.com/travisjeffery/jocko: no Go files in /home/fred/gopath/src/github.com/travisjeffery/jocko"

It does not seem to cause any subsequent difficulties.

**Comment by travisjeffery** [comment]
yeah it's fine, that's just the go cli complaining.
