### ISSUE TITLE
use go module build?

### ISSUE THREAD

**Issue by thinkerou** [travisjeffery/jocko#149]
Hi, @travisjeffery I found use `dep` build project now, the project need to use `go module`(go 1.11)?
If the project require go version >= go 1.11, I think it need. ok? I can commit one pull request.
thanks!

**Comment by travisjeffery** [comment]
@thinkerou yeah I'd like to start using go module. Please make a PR!

**Comment by sah4ez** [comment]
Hi everyone!
See my PR #155
