### ISSUE TITLE
clean up cmdline arguments & defaults

### ISSUE THREAD

**Issue by teepark** [travisjeffery/jocko#21]
The main package command line arguments are currently done in a mix of styles:

- `tcpaddr` is an `ip:port` address with no default
- `raftaddr` and `raftport` together form the bind location for the raft protocol
- `serfport` is just the port with a default value -- the IP is hard-coded to `0.0.0.0`.
- `raftdir` is actually ignored, instead `logdir/raft` [is always used](https://github.com/travisjeffery/jocko/blob/3dbfe17d4b3a97964488c9d23bd3f246dda85b84/broker/raft.go#L53)

I propose getting rid of `raftdir`, and standardizing on `ip:port` arguments with defaults serving on all interfaces (`0.0.0.0`). Ideally the beginner, experimenting, can get started with a single-node cluster by just running `jocko`.

Would you accept a PR like this?

**Comment by travisjeffery** [comment]
Yep, I'd accept a PR. Thanks.

**Comment by travisjeffery** [comment]
Ah I ended up writing one. Let me know what you think about that. The Raft one has to be set to 127.0.0.1 and set at times when you want to advertise otherwise. Hashicorp's Consul works the same way.

**Comment by teepark** [comment]
Nice! I'll go ahead and make a PR from my WIP, see if there's anything worth borrowing there :)
