### ISSUE TITLE
go test github.com/travisjeffery/jocko/server deletes $TMPDIR

### ISSUE THREAD

**Issue by davecheney** [travisjeffery/jocko#24]
https://github.com/travisjeffery/jocko/blob/master/server/server_test.go#L189
https://github.com/travisjeffery/jocko/blob/master/server/server_test.go#L222

**Comment by dgryski** [comment]
You probably want https://golang.org/pkg/io/ioutil/#TempDir instead.

**Comment by travisjeffery** [comment]
Woh, thanks. Yeah I [use](https://github.com/travisjeffery/jocko/blob/b2996a65ed6ddb6d33f488676a6f891bda2d5f46/server/server_test.go#L34) `ioutil.TempDir` to create the dir that's actually used (`dataDir`). Just a stupid couple of lines there. At least I can tell people I've been shamed by Dave Cheney in an issue in the Go repo.
