### ISSUE TITLE
Error opening raft store: missing port in address

### ISSUE THREAD

**Issue by stefanscheidt** [travisjeffery/jocko#26]
Hi,

I just followed the samara/README.md and got this error:

```
$ go run main.go
Error opening raft store: missing port in address
exit status 1
```

I'm using go version go1.7.5 darwin/amd64 on macOS Sierra 10.12.3 (16D32).

I also tried `go get -u github.com/kardianos/govendor` and `govendor sync` - inspired by your Makefile - assuming some dependency version issues but got

```
$ govendor sync
# cd .; git clone https://gopkg.in/alecthomas/kingpin.v2 /Users/stefanscheidt/Code/Go/.cache/govendor/gopkg.in/alecthomas/kingpin.v2
Cloning into '/Users/stefanscheidt/Code/Go/.cache/govendor/gopkg.in/alecthomas/kingpin.v2'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
Error: Remotes failed for:
	Failed for "gopkg.in/alecthomas/kingpin.v2" (failed to clone repo): exit status 128
```

**Comment by travisjeffery** [comment]
Hey thanks, I changed the params the other day and forgot to update the example. Give it another try and let me know if it works.

**Comment by stefanscheidt** [comment]
Hello, thanks for the super quick response. Now it works:

```
...
producer and consumer worked! 15 messages ok
```

Thanks!

**Comment by stefanscheidt** [comment]
By the way, the problem with `govendor sync` could be fixes with a workaround I found [here](https://github.com/niemeyer/gopkg/issues/50):

```
git config --global http.https://gopkg.in.followRedirects true
```

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.

**Comment by stefanscheidt** [comment]
Cool. Thanks!
