### ISSUE TITLE
suspect usage of sort.Search

### ISSUE THREAD

**Issue by robbiev** [travisjeffery/jocko#38]
I was reading the source and came across this in `commitlog/util.go`:

```go
func findSegment(segments []*Segment, offset int64) (*Segment, int) {
	idx := sort.Search(len(segments), func(i int) bool {
		return segments[i].BaseOffset > offset
	}) - 1

	if idx < 0 {
		return nil, idx
	}

	return segments[idx], idx
}
```

[The documentation for sort.Search](https://golang.org/pkg/sort/#Search) says:

>Search returns the first true index. If there is no such index, Search returns n. (Note that the "not found" return value is not -1 as in, for instance, strings.Index.)

So intuitively it appears that this code should check for `idx == len(segments)`. Or if you take into account the `-1` in the code listed above it would be `idx == len(segments)-1`.

I found another usage of `sort.Search` in `commitlog/segment.go` (`findEntry`) that also doesn't check this condition.

**Comment by travisjeffery** [comment]
Fixed thanks.
