### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by skotchpine** [travisjeffery/jocko#50]
I'm interested in adding tests to help match necessary Kafka features and enable a trusty integration, but unsure where to start. I've run all the tests successfully through `cd $GOPATH/src/github.com/travisjeffery/jocko; make`, and read through a few. What is best at this early stage? @travisjeffery, I summon you!

**Comment by travisjeffery** [comment]
@skotchpine how about testing the api requests and responses – that'll set us up for adding the request versioning. You can look at [how Sarama does it](https://github.com/Shopify/sarama/blob/master/consumer_metadata_request_test.go) as an example.

**Comment by skotchpine** [comment]
Looks like a good chunk of code. I'll start there

**Comment by skotchpine** [comment]
I'm going to hold on the versioning tests while @mrcrgl does his work. I've got a few dumb table tests for ApiKeys and ErrorCodes, will push when there's something more useful.
