### ISSUE TITLE
Different logging library

### ISSUE THREAD

**Issue by BasPH** [travisjeffery/jocko#58]
Is there a reason for using `travisjeffery/simplelog` library for logging? Logrus would give us much more logging features. For jocko specific, I think different logging levels and logging output options that Logrus provides would come in handy.

**Comment by travisjeffery** [comment]
Just wasn't important at the time. Now'd be a good time to get serious about it and Logrus works for me. Do you wanna take it on?

**Comment by travisjeffery** [comment]
I think we should go with https://github.com/uber-go/zap tho

**Comment by BasPH** [comment]
Didn't know about zap, looks nice. I'll give it a try.

**Comment by travisjeffery** [comment]
Done in https://github.com/travisjeffery/jocko/pull/84
