### ISSUE TITLE
server uses the same net.listener for http server and jocko tcp server?

### ISSUE THREAD

**Issue by smallnest** [travisjeffery/jocko#60]
https://github.com/travisjeffery/jocko/blob/master/server/server.go#L88-110

It looks jocko and http server use the same net.Listener and that means there are two goroutines to do `s.ln.Accept()`. Maybe some sent kafka messages have been handled by http server and it thinks them are wrong requests?

**Comment by travisjeffery** [comment]
Thanks @smallnest !
