### ISSUE TITLE
Cannot run serf_test.Test_Membership()

### ISSUE THREAD

**Issue by BasPH** [travisjeffery/jocko#63]
The test `Test_Membership` in serf_test.go keeps failing on me with error:
```
--- FAIL: Test_Membership (0.01s)
        Error Trace:    serf_test.go:37
	Error:		Received unexpected error Failed to create memberlist: Could not set up network transport: Failed to start UDP listener on "0.0.0.0" port 7948: listen udp 0.0.0.0:7948: bind: address already in use
```

I cannot figure out why I'm getting this error. I trace the bind down to the point [where it calls `net.ListenUDP`](https://github.com/hashicorp/memberlist/blob/master/net_transport.go#L96) on UDP port 7948, set a breakpoint at this line and don't see any listening UDP connections on port 7948 at this point:
```
basph@MBP:~$ lsof -i -n -P | grep 794
___Test_M 6478 bas    8u  IPv6 0x21aa5a91cbda343b      0t0  TCP *:7947 (LISTEN)
___Test_M 6478 bas    9u  IPv6 0x21aa5a91c9953d5b      0t0  UDP *:7947
___Test_M 6478 bas   10u  IPv6 0x21aa5a91cbda2efb      0t0  TCP *:7948 (LISTEN)
```

Any ideas?

**Comment by travisjeffery** [comment]
You might have better luck using netstat:

```
netstat -tulnvp udp | grep 7948
```

I'm gonna close since this isn't a jocko issue, it's something else running on your computer.
