### ISSUE TITLE
Code Coverage Plugin

### ISSUE THREAD

**Issue by ryanstinson** [travisjeffery/jocko#69]
@travisjeffery I would like to enable https://codecov.io/ on the repo. I don't think I can perform all the required steps to set it up but I can assist and add the required test setup. What do you think?

**Comment by travisjeffery** [comment]
Good idea, I've set it up. Let's get the coverage up before we add the badge to the README though :D

**Comment by jacktuck** [comment]
@travisjeffery I messaged on gitter before looking at these issues - i will _try_ and help with coverage too :)
