### ISSUE TITLE
Go install fails with Go 1.8.3 on Darwin

### ISSUE THREAD

**Issue by alexellis** [travisjeffery/jocko#80]
I was trying to install the binary and got this error:

```
$ go install github.com/travisjeffery/jocko

# github.com/travisjeffery/jocko
./jocko.go:33: syntax error: unexpected = in type declaration
```

$ go version:

```
go version go1.8.3 darwin/amd64
```

Have you thought of doing releases of the binary through GitHub? We do this on OpenFaaS and you're welcome to cookie-cut the process, it's immensely useful. ( example: https://github.com/openfaas/faas-cli )

**Comment by alexellis** [comment]
Using the Makefile also fails with errors like:

```
dep ensure
go test -v ./...
vendor/github.com/armon/go-metrics/circonus/circonus.go:9:2: cannot find package "github.com/circonus-labs/circonus-gometrics" in any of:
```

You don't even have circonus-labs in your lock file..

**Comment by travisjeffery** [comment]
You need go 1.9 for type aliases. I put a 0.0.1 release. I'd only use it for testing atm.

**Comment by alexellis** [comment]
Looked like it was a single type alias on one line that caused the breakage. You could keep compatibility by reversing that, or state clearly that Go 1.9 is needed 👍
