### ISSUE TITLE
Ditch the gommap

### ISSUE THREAD

**Issue by ivanjaros** [travisjeffery/jocko#92]
Hi,
I just wanted to test the commit log but it looks like the index depends on the https://github.com/tysonmote/gommap which hasn't been updated for almost 5 years and does not work on Windows at all.

**Comment by travisjeffery** [comment]
If someone writes a better one, or I clear through a 1000 things with higher priority

**Comment by ivanjaros** [comment]
https://github.com/golang/exp/tree/master/mmap

**Comment by thumbsized** [comment]
🤷🏻‍♂️

**Comment by thumbsized** [comment]
https://github.com/dgraph-io/badger/blob/master/y/mmap_windows.go
